version: '2.4'

services:
  sharepointrestproxy:
    image: sharepointrestproxy
    container_name: sharepointrestproxy
    tty: true
    ports:
      - 9094:9990
    environment:
      - USER=${USER}
      - PASSWD=${PASSWD}
      #- DUMP_DIRECTORY=${DUMP_DIRECTORY}
    volumes:
      - ./krb5.conf:/etc/krb5.conf
      - ./login.conf:/app/login.conf
      - ./sharepoint.keytab:/app/sharepoint.keytab
    mem_limit: 512m
    networks:
      sharepointrestproxy:
    restart: ${RESTART}

networks:
  sharepointrestproxy:
    ipam:
      driver: default
